### PR TITLE
Library review according to the KLC

### PR DESCRIPTION
**Pull request by pedrominatel**
Library review according to the KLC.

Closes: https://github.com/espressif/kicad-libraries/issues/57

### CODE REVIEW

**Comment by JustinOng** [comment]
Thank you very much! I've taken a quick look through the symbols and found a couple of small things:
- Stacked pins should be of type `passive` so that they do not become global labels
- Power rails like `VDD3P3` and `VDDA` on `ESP32`, `ESP32-C3`, `ESP32-PICO-V3`, `ESP32-S2` and `ESP32-S3` arn't stacked
- I assume `ESP32-S3-DevKitC` having pins unstacked is intentional to reflect the physical layout

Otherwise, looks good to me!

**Comment by pedrominatel** [comment]
Thank you @JustinOng for your quick response. I'll change it according to your review.

**Comment by pedrominatel** [comment]
PTAL @JustinOng.

**Comment by JustinOng** [comment]
Yep, looks good to me!

**Pull request merged**
