### PR TITLE
PCM packaging fixes

### PR DESCRIPTION
**Pull request by JarrettR**
When trying to submit this to the official KiCad PCM, the CI pipeline fails. This PR should fix that.

image

1. Removed spurious `/` from the metadata filename
2. Moved extra PCM installation instruction images from `resources` into `docs` instead
3. Updated `README` to reflect the new image locations

The next release should fix the build zip and we should be able to merge into the PCM

### CODE REVIEW

**Comment by JarrettR** [comment]
Actually, the work isn't quite done. The CI pipeline wants to validate every version, but will fail for the same reasons on 2.0.0 to 2.0.4. Additionally, here is the more complete error log (of the latest version only):

```
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S2-WROOM.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-MINI-1.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S2-WROVER.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-WROVER-E.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-WROOM-32E_No-Cover.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S2-SOLO-U.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S2-MINI-1U.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-C3-MINI-1U.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S3-MINI-1.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-C3-WROOM-02.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S2-MINI-1.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S3-WROOM-1.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S3-WROOM-1U.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-WROOM-32E.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-S2-SOLO.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-C3-MINI-1.STEP"
Version 2.0.4: package contains extra file "3dmodels/espressif.3dshapes/ESP32-C3-WROOM-02U.STEP"
Version 2.0.4: package contains extra file "resources/pcm_install_step-4.png"
Version 2.0.4: package contains extra file "resources/pcm_install_step-2.png"
Version 2.0.4: package contains extra file "resources/pcm_install_step-3.png"
Version 2.0.4: package contains extra file "resources/pcm_install_step-1.png"
Version 2.0.4: package contains extra file "/metadata.json"
Version 2.0.4: package has no metadata.json
```


Proposal:
Remove the earlier versions from the [metadata.json](https://github.com/espressif/kicad-libraries/blob/main/metadata.json)
This is will force users to manually install it as before, with effectively no change. It feels slightly dirty, though, so I don't want to do it myself with no feedback.

I'm not sure about the 3D models at the moment.

**Comment by pedrominatel** [comment]
Hi @JarrettR, thank you for your contribution.

We can remove the old versions from the metadata or we can backport the changes, but I don't think this extra work will be needed.
Regarding the extra 3D models, we can remove the `STEP` files if the `WRL` is present for the same footprint, but we need to double-check if the `WRL` file is the one selected for the footprint in the properties.

**Comment by JarrettR** [comment]
Okay, I would expect this one to work on the next release.

I've removed the metadata file as discussed. Your GH action will regenerate it on release.

The other issue is that the KiCad CI pipeline requires 3D models to have a lowercase extensions. Because many of the CAD options seem to prefer uppercase extensions, I submitted a [merge request](https://gitlab.com/kicad/addons/metadata/-/merge_requests/270) to change that requirement, but it doesn't seem like that will be accepted at this time. So, the STEP extensions in this repo must be lowercase.

**Comment by pedrominatel** [comment]
@JarrettR, in order to avoid any confusion with the naming convention, we can change the file names to lowercase on our side. I don't think it will be necessary the MR you proposed.

**Comment by JarrettR** [comment]
👍 
Reverted that commit

**Pull request merged**
