### PR TITLE
Add ESP32-C6-DevkitC-1 symbol and footprint

### PR DESCRIPTION
**Pull request by nickoe**
Fixes https://github.com/espressif/kicad-libraries/issues/99

The symbol and footprint are derived from the ESP32-S2-DevkitC-1, as I thought it was most similar. Please review.

image

image

### CODE REVIEW

**Comment by nickoe** [comment]
@pedrominatel  In kicad 7 we can add alternative pin definitions. Should I attempt to add some of those as well?

In this one I added /foo to some pins, but as a subjective judgement. Bootstrapping pins, UART0, and ADC. Is there any guideline for preference established for this repo? I don't see one in particular.

**Comment by pedrominatel** [comment]
Hi @nickoe,

I think we can try to use this feature on this symbol and see if we change the others.
Can you explain more about the "guideline for preference"?

Thanks

**Review by pedrominatel — APPROVED** [review]
LGTM

**Comment by pedrominatel** [comment]
Hi @nickoe, can you fix the conflict? Now we are moving to PCM approach and this new symbol and footprint will be included in the next release.

**Comment by nickoe** [comment]
@pedrominatel Yeah, I will fix it. I will also add an update with the alternate pin definitions. I am considering to remove all the pin silkscreen labels. They are a lot in the way if one decides to mount stuff under the module.

**Comment by nickoe** [comment]
Mm, I did not intentionally close this pull request.

**Comment by pedrominatel** [comment]
Thanks @nickoe, I'll take a look and merge as soon as possible.

**Review by pedrominatel — APPROVED** [review]
LGTM

**Comment by tomlevisse** [comment]
Is there a 3D model ?

**Comment by nickoe** [comment]
I don't have one. I don't intend to fabricate one. Feel free to attempt that.  I wonder if the other 3D models are contributor generared or of they are exports from espressiff.

**Pull request merged**
